---
title: "Relatório Informativo sobre Dengue"
author: "Vigilância Epidemiológica do Estado de Rosas"
date: '2022-07-11'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

O **Departamento de Vigilância Epidemiológica do Estado de Rosas**, por meio deste boletim informativo^1^, apresenta informações gerais sobre a dengue^2^, assim como uma breve análise dos dados históricos relativos à situação epidemiológica da dengue no Estado de Rosas. Entre 2007 e 2012, o município registrou _N_ casos confirmados de dengue e _M_ óbitos. A distribuição dos casos confirmados por semana epidemiológica é apresentada na *Figura 1*. O número de casos por classificação final são apresentados na *Tabela 1*.

^1^ Este relatório foi produzido utilizando a linguagem `RMarkdown`.

^2^ As informações sobre esta doença foram baseadas em conteúdo disponibilizado pelo Ministério da Saúde. Para obter mais informações, acesse [este link](https://www.gov.br/saude/pt-br/assuntos/saude-de-a-a-z/d/dengue).

## Introdução

1. O que é Dengue

A dengue é a arbovirose urbana mais prevalente nas Américas, principalmente no Brasil. É uma doença febril que tem se mostrado de grande importância em saúde pública nos últimos anos. O vírus dengue (DENV) é um arbovírus transmitido pela picada da fêmea do mosquito _Aedes aegypti_ e possui quatro sorotipos diferentes (DENV-1, DENV-2, DENV-3 e DENV-4).

i. Principais Sintomas

* Febre alta > 38°C.
* Dor no corpo e articulações
* Dor atrás dos olhos.
* Mal estar.
* Falta de apetite.
* Dor de cabeça.
* Manchas vermelhas no corpo.

ii. Transmissão

O vírus da dengue (DENV) pode ser transmitido ao homem principalmente por via vetorial, pela picada de fêmeas de _Aedes aegypti_ infectadas, no ciclo urbano humano–vetor–humano. Os relatos de transmissão por via vertical (de mãe para filho durante a gestação) e transfusional são raros.

iii. Diagnóstico

* Métodos diretos

  + Pesquisa de vírus (isolamento viral por inoculação em células);

  + Pesquisa de genoma do vírus da dengue por transcrição reversa seguida de reação em cadeia da polimerase (RT-PCR);

* Métodos indiretos

  + Pesquisa de anticorpos IgM por testes sorológicos (ensaio imunoenzimático – ELISA)

  + Teste de neutralização por redução de placas (PRNT);

  + Inibição da hemaglutinação (IH);

  + Pesquisa de antígeno NS1 (ensaio imunoenzimático – ELISA);

  + Patologia: estudo anatomopatológico seguido de pesquisa de antígenos virais por imuno-histoquímica (IHQ).
  
## Análises

### 1. Distribuição de casos por semana epidemiológica

### 2. Número de casos por classificação final


